name: pierobon
favicon: null
layout_spectrum: 0.28597
typography_spectrum: 0.63504
title: Marco Pierobon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77086951-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddded9'
    - '#aca9a0'
    - '#677b70'
    - '#254435'
    - '#151e1b'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
