name: pierobon
favicon: null
layout_spectrum: 0.77326959813945
typography_spectrum: 0.8950451093260199
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6899892343208194
  lightness: 0.7151374793611467
  saturation: 0.04984565475024283
  rhythmicContrast: 0.7255037010181695
purpose: []
