name: pierobon
favicon: null
layout_spectrum: 0.66305
typography_spectrum: 0.53191
title: Marco Pierobon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#56462f'
    - '#a99c79'
    - '#e8e7e2'
    - '#706551'
    - '#322f1e'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
